// get all teachers data-
export const GET_ALL_TEACHERS_REQUEST = "GET_ALL_TEACHERS_REQUEST";
export const GET_ALL_TEACHERS_SUCCESS = "GET_ALL_TEACHERS_SUCCESS";
export const GET_ALL_TEACHERS_ERROR = "GET_ALL_TEACHERS_ERROR";

// get single teacher data-
export const GET_SINGLE_TEACHER_REQUEST = "GET_SINGLE_TEACHER_REQUEST";
export const GET_SINGLE_TEACHER_SUCCESS = "GET_SINGLE_TEACHER_SUCCESS";
export const GET_SINGLE_TEACHER_ERROR = "GET_SINGLE_TEACHER_ERROR";

// post teacher data-
export const POST_TEACHERS_REQUEST = "POST_TEACHERS_REQUEST";
export const POST_TEACHERS_SUCCESS = "POST_TEACHERS_SUCCESS";
export const POST_TEACHERS_ERROR = "POST_TEACHERS_ERROR";

// post teacher data-
export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_ERROR = "UPDATE_TEACHER_ERROR";

// delete teacher data-
export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_ERROR = "DELETE_TEACHER_ERROR";