// get all students data-
export const GET_ALL_STUDENTS_REQUEST = "GET_ALL_STUDENTS_REQUEST";
export const GET_ALL_STUDENTS_SUCCESS = "GET_ALL_STUDENTS_SUCCESS";
export const GET_ALL_STUDENTS_ERROR = "GET_ALL_STUDENTS_ERROR";

// get single student data-
export const GET_SINGLE_STUDENT_REQUEST = "GET_SINGLE_STUDENT_REQUEST";
export const GET_SINGLE_STUDENT_SUCCESS = "GET_SINGLE_STUDENT_SUCCESS";
export const GET_SINGLE_STUDENT_ERROR = "GET_SINGLE_STUDENT_ERROR";

// post student data-
export const POST_STUDENTS_REQUEST = "POST_STUDENTS_REQUEST";
export const POST_STUDENTS_SUCCESS = "POST_STUDENTS_SUCCESS";
export const POST_STUDENTS_ERROR = "POST_STUDENTS_ERROR";

// post student data-
export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";

// delete student data-
export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_ERROR = "DELETE_STUDENT_ERROR";