// get all accessories data-
export const GET_ACCESSORIES_REQUEST = "GET_ACCESSORIES_REQUEST";
export const GET_ACCESSORIES_SUCCESS = "GET_ACCESSORIES_SUCCESS";
export const GET_ACCESSORIES_ERROR = "GET_ACCESSORIES_ERROR";

// post accessories data-
export const POST_ACCESSORIES_REQUEST = "POST_ACCESSORIES_REQUEST";
export const POST_ACCESSORIES_SUCCESS = "POST_ACCESSORIES_SUCCESS";
export const POST_ACCESSORIES_ERROR = "POST_ACCESSORIES_ERROR";

// update accessories data-
export const UPDATE_ACCESSORIES_REQUEST = "UPDATE_ACCESSORIES_REQUEST";
export const UPDATE_ACCESSORIES_SUCCESS = "UPDATE_ACCESSORIES_SUCCESS";
export const UPDATE_ACCESSORIES_ERROR = "UPDATE_ACCESSORIES_ERROR";

// delete accessories data-
export const DELETE_ACCESSORIES_REQUEST = "DELETE_ACCESSORIES_REQUEST";
export const DELETE_ACCESSORIES_SUCCESS = "DELETE_ACCESSORIES_SUCCESS";
export const DELETE_ACCESSORIES_ERROR = "DELETE_ACCESSORIES_ERROR";